import Head from 'next/head'



export const MetaHead = ({ title }: { title?: string }) => {
    return (
        <Head>
            <title>{`Sigma Fit${title ? ' - ' + title : ''}`}</title>
            <meta name="description" content="Generated by Sigma Fit" />
            <link rel="icon" href="/favicon.ico" />
            <meta name='viewport' content='minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover' />

            <meta name='application-name' content='Sigma Fit' />
            <meta name='apple-mobile-web-app-capable' content='yes' />
            <meta name='apple-mobile-web-app-status-bar-style' content='default' />
            <meta name='apple-mobile-web-app-title' content='Sigma Fit' />
            <meta name='description' content='Workout tracking made easy!' />
            <meta name='mobile-web-app-capable' content='yes' />

            <link rel='manifest' href='/manifest.json' />
            <link rel='shortcut icon' href='/favicon.ico' />

        </Head>
    )
}
