import Head from "next/head";

export const MetaHead = ({ title }: { title?: string }) => {
  return (
    <Head>
      <title>{`Sigma Fit${title ? " - " + title : ""}`}</title>
      <meta name="description" content="Generated by Sigma Fit" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        name="viewport"
        content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
      />

      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/icons/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/icons/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/icons/favicon-16x16.png"
      />
      <link
        rel="mask-icon"
        href="/icons/safari-pinned-tab.svg"
        color="#000000"
      />
      <meta name="msapplication-TileColor" content="#2d89ef" />
      <meta name="theme-color" content="#f9f8f0" />

      <meta name="application-name" content="Sigma Fit" />
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      <meta name="apple-mobile-web-app-title" content="Sigma Fit" />
      <meta name="description" content="Workout tracking made easy!" />
      <meta name="mobile-web-app-capable" content="yes" />

      <link rel="manifest" href="/manifest.json" />
    </Head>
  );
};
