import Head from 'next/head'



export const MetaHead = () => {
    return (
        <Head>
            <title>Sigma Fit</title>
            <meta name="description" content="Generated by Sigma Fit" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}
